### ISSUE TITLE
cannot upgrade this dependency using yarn

### ISSUE THREAD

**Issue by bilo-io** [mapbox/hast-util-table-cell-style#3]
I tried upgrading my dependencies using `yarn`, and this was the result:

```
yarn upgrade v1.6.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Couldn't find package "@mapbox/hast-util-table-cell-style@^0.1.3" required by "remark-react@^4.0.0" on the "npm" registry.
```
Specifically, my repo depends on `remark-react` which depends on this. It was updated 6 days ago (from the time of creating this issue). Pretty much since then my team and I have been experiencing this issue.

This must be an issue related to `yarn`, rather than `npm`. 

Any ideas?

**Comment by davidtheclark** [comment]
@bilo-io: I see it at https://www.npmjs.com/package/@mapbox/hast-util-table-cell-style, and that page says it's public and version 0.1.3 is published. Also Travis in remark-react hasn't had any trouble installing the package. If I locally `yarn add @mapbox/hast-util-table-cell-style` it installs without any complaint.

Because of all that, I suspect that the package is published correctly, and there's something weird going on on your end. I'm not sure how I could help debug, though 🤷‍♂️

**Comment by bilo-io** [comment]
@davidtheclark I realised it is actually something related to my `.npmrc` ... if I temporarily remove that, upgrading works. So the issue does not seem to lie on your side. But if you could do me a solid, please try upgrading this as a dependency in a repo that has an `.npmrc` on your side.

**Comment by davidtheclark** [comment]
@bilo-io I don't use `.npmrc` in repos so won't be able to help there. But might be a good question for Stack Overflow or some other forum.
